### ISSUE TITLE
HTTP Error 400 for certain OTT IDs

### ISSUE THREAD

**Issue by f-heeger** [OpenTreeOfLife/pyopentree#3]
When using gol_node_info, I get a HTTP Error for OTT ID 121703. 

According to the browser version this is a valid OTT ID (see [here](https://tree.opentreeoflife.org/opentree/argus/ottol@121703/Clavariopsis-aquatica)). 
Other IDs (like 10732 and 810751) work. I also get correct results for 121703 if I use curl to build the request (like described [here](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#graph)).

I am running Python 2.7.6 on ubuntu 14.04.

The exception contains the following information:
> {
>   "message" : "Could not find any graph nodes corresponding to the ott id provided.",
>   "exception" : "IllegalArgumentException",
>   "fullname" : "java.lang.IllegalArgumentException",
>   "stacktrace" : [ "opentree.plugins.graph.node_info(graph.java:141)", "java.lang.reflect.Method.invoke(Method.java:497)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:57)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:497)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
> }

**Comment by mtholder** [comment]
I get this error if I run a cURL against the tree that is on the testing devapi site, but not if I run against the "real" site:
    
    curl -X POST -H "Content-Type":"application/json" -H "Accept":"application/json" http://devapi.opentreeoflife.org/v2/graph/node_info --data '{"include_lineage": false, "ott_id": 121703}'
    {
      "message" : "Could not find any graph nodes corresponding to the ott id provided.",
      "exception" : "IllegalArgumentException",
      "fullname" : "java.lang.IllegalArgumentException",
      "stacktrace" : [ "opentree.plugins.graph.node_info(graph.java:141)", "java.lang.reflect.Method.invoke(Method.java:497)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:57)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:497)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
    }
    curl -X POST -H "Content-Type":"application/json" -H "Accept":"application/json" http://api.opentreeoflife.org/v2/graph/node_info --data '{"include_lineage": false, "ott_id": 121703}'
    {
      "tree_id" : "opentree3.0",
      "num_synth_tips" : 1,
      "name" : "Clavariopsis aquatica",
      "rank" : "species",
      "ott_id" : 121703,
      "num_tips" : 1,
      "tree_sources" : [ ],
      "tax_source" : "if:215182,ncbi:253306,gbif:5262405,irmng:11080616",
      "synth_sources" : [ {
        "git_sha" : "",
        "tree_id" : "",
        "study_id" : "taxonomy"
      } ],
      "node_id" : 3319342,
      "in_synth_tree" : true
    }

**Comment by f-heeger** [comment]
Yes. Thank you. I was using the global functions and not aware of the possibility to set the base_url. Now it is working.

**Comment by jeetsukumaran** [comment]
Should we change the default URL?

**Comment by mtholder** [comment]
probably.

**Comment by jeetsukumaran** [comment]
OK 907eeeb
